/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObjectId } from './objectId';
import { ContactInfo } from './contactInfo';
import { RequestStatus } from './requestStatus';


export interface AssociationRequestDTO { 
    _id?: ObjectId;
    associationName?: string;
    associationConfirmed?: boolean;
    associationSQLId?: string;
    motivation?: string;
    status?: RequestStatus;
    updatedAt?: string;
    createdAt?: string;
    contactInfo?: ContactInfo;
    attachments?: Array<string>;
    location?: string;
}
export namespace AssociationRequestDTO {
}


