/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OpCode } from './opCode';
import { Utente } from './utente';


export interface AuthResponse { 
    bearerToken?: string;
    opCode?: OpCode;
    message?: string;
    user?: Utente;
}
export namespace AuthResponse {
}


