/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestStatus } from './requestStatus';
import { RequestType } from './requestType';


export interface BaseRequest { 
    requestId?: string;
    associationReqId?: string;
    associationSQLId?: string;
    associationConfirmed?: boolean;
    associationName?: string;
    requestType?: RequestType;
    motivation?: string;
    status?: RequestStatus;
    tags?: Array<string>;
    updatedAt?: string;
    createdAt?: string;
}
export namespace BaseRequest {
}


