/**
 * nautilus-backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Charset { 
    name?: string;
    aliases?: Array<string>;
    aliasSet?: Set<string>;
    registered?: boolean;
}

