/**
 * nautilus-backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Origin } from './origin';
import { Part } from './part';


export interface Expression { 
    namespace?: string;
    parts?: Array<Part>;
    literal?: boolean;
    literalValue?: any | null;
    origin?: Origin;
    generatedId?: number;
}

