/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InventoryItemCategoryDTO } from './inventoryItemCategoryDTO';


export interface InventoryItemDTO { 
    id?: number;
    name?: string;
    itemCategory?: InventoryItemCategoryDTO;
    availableQuantity?: number;
}

