/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InventoryItem } from './inventoryItem';
import { Warehouse } from './warehouse';
import { Association } from './association';
import { InventoryBoxSize } from './inventoryBoxSize';


export interface InventoryBox { 
    id?: number;
    full?: boolean;
    fkAssociation?: Association;
    fkWarehouse?: Warehouse;
    inventoryItems?: Set<InventoryItem>;
    fkSize?: InventoryBoxSize;
    currentSize?: number;
}

