/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InventoryChangeDTO { 
    itemId?: string;
    itemName?: string;
    previousQuantity?: number;
    requestedQuantity?: number;
    changeType?: string;
}

