/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InventoryBoxSizeDTO } from './inventoryBoxSizeDTO';
import { InventoryItemDTO } from './inventoryItemDTO';
import { WarehouseDTO } from './warehouseDTO';


export interface InventoryBoxDTO { 
    id?: number;
    full?: boolean;
    fkWarehouse?: WarehouseDTO;
    inventoryItems?: Array<InventoryItemDTO>;
    fkSize?: InventoryBoxSizeDTO;
    currentSize?: number;
}

