/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InventoryChangeDTO } from './inventoryChangeDTO';
import { ObjectId } from './objectId';


export interface InventoryRequestDTO { 
    _id?: ObjectId;
    inventoryChanges?: Array<InventoryChangeDTO>;
    approvedBy?: string;
    approvalDate?: string;
    requestSource?: string;
}

