/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InventoryItemDTO } from './inventoryItemDTO';
import { InventoryItemCategoryDTO } from './inventoryItemCategoryDTO';


export interface ItemMgmtResponse { 
    categories?: Array<InventoryItemCategoryDTO>;
    items?: Array<InventoryItemDTO>;
}

