/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InventoryItemCategory } from './inventoryItemCategory';
import { InventoryItem } from './inventoryItem';


export interface ItemMgmtResponse { 
    categories?: Array<InventoryItemCategory>;
    items?: Array<InventoryItem>;
}

