/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObjectId } from './objectId';
import { ContactInfo } from './contactInfo';
import { RequestStatus } from './requestStatus';
import { RequestType } from './requestType';


export interface JoinRequest { 
    requestId?: string;
    associationReqId?: string;
    associationSQLId?: string;
    associationConfirmed?: boolean;
    associationName?: string;
    requestType?: RequestType;
    motivation?: string;
    status?: RequestStatus;
    tags?: Array<string>;
    updatedAt?: string;
    createdAt?: string;
    _id?: ObjectId;
    date?: string;
    contactInfo?: ContactInfo;
    attachments?: Array<string>;
    location?: string;
}
export namespace JoinRequest {
}


