/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObjectId } from './objectId';
import { ContactInfo } from './contactInfo';
import { History } from './history';


export interface JoinRequest { 
    requestId?: ObjectId;
    associationName?: string;
    timestamp?: string;
    date?: string;
    motivation?: string;
    contactInfo?: ContactInfo;
    category?: string;
    urgency?: string;
    attachments?: Array<string>;
    location?: string;
    status?: string;
    assignedAdmin?: string;
    priority?: string;
    actionTaken?: string;
    resolutionTimestamp?: string;
    requestSource?: string;
    tags?: Array<string>;
    processingTime?: number;
    history?: Array<History>;
}

