/**
 * nautilus-backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Locale { 
    language?: string;
    script?: string;
    country?: string;
    variant?: string;
    extensionKeys?: Set<string>;
    unicodeLocaleAttributes?: Set<string>;
    unicodeLocaleKeys?: Set<string>;
    iSO3Language?: string;
    iSO3Country?: string;
    displayLanguage?: string;
    displayScript?: string;
    displayCountry?: string;
    displayVariant?: string;
    displayName?: string;
}

