/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Reparti } from './reparti';
import { ShiftPreference } from './shiftPreference';


export interface Nurse { 
    id?: number;
    firstName?: string;
    lastName?: string;
    age?: number;
    repartoID?: Reparti;
    shiftPreferenceID?: ShiftPreference;
}

