/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ObjectId { 
    timestamp?: number;
    counter?: number;
    randomValue1?: number;
    randomValue2?: number;
    date?: string;
}

