/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OpCode = 'SUCCESS' | 'ERROR';

export const OpCode = {
    Success: 'SUCCESS' as OpCode,
    Error: 'ERROR' as OpCode
};

