/**
 * nautilus-backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Variant } from './variant';


export interface Origin { 
    line?: number;
    lineCharacterStart?: number;
    lineCharacterEnd?: number;
    templateId?: string;
    templateGeneratedId?: string;
    variant?: Variant | null;
    synthetic?: boolean;
}

