/**
 * nautilus-backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Origin } from './origin';
import { Expression } from './expression';


export interface ParameterDeclaration { 
    typeInfo?: string;
    key?: string;
    defaultValue?: Expression;
    origin?: Origin;
}

