/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ProjectStatus = 'ALLOCATED' | 'EXECUTING' | 'COMPLETED' | 'FAILED';

export const ProjectStatus = {
    Allocated: 'ALLOCATED' as ProjectStatus,
    Executing: 'EXECUTING' as ProjectStatus,
    Completed: 'COMPLETED' as ProjectStatus,
    Failed: 'FAILED' as ProjectStatus
};

