/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectStep } from './projectStep';
import { ProjectStatus } from './projectStatus';
import { ProjectItem } from './projectItem';
import { ObjectId } from './objectId';
import { ProjectAllocatedResources } from './projectAllocatedResources';
import { RequestStatus } from './requestStatus';


export interface ProjectRequest { 
    _id?: ObjectId;
    associationReqId?: string;
    associationSqlId?: number;
    projectName?: string;
    description?: string;
    budget?: number;
    requiredItemsSQLId?: Array<ProjectItem>;
    projectPlan?: Array<ProjectStep>;
    projectStatus?: ProjectStatus;
    status?: RequestStatus;
    updatedAt?: string;
    createdAt?: string;
    allocationId?: string;
    allocatedResources?: ProjectAllocatedResources;
}
export namespace ProjectRequest {
}


