/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectAllocatedResourcesDTO } from './projectAllocatedResourcesDTO';
import { ProjectStatus } from './projectStatus';
import { ObjectId } from './objectId';
import { ProjectItemDTO } from './projectItemDTO';
import { ProjectStepDTO } from './projectStepDTO';


export interface ProjectRequestDTO { 
    _id?: ObjectId;
    projectName?: string;
    description?: string;
    budget?: number;
    requiredItemsSQLId?: Array<ProjectItemDTO>;
    projectPlan?: Array<ProjectStepDTO>;
    projectStatus?: ProjectStatus;
    allocationId?: string;
    allocatedResources?: ProjectAllocatedResourcesDTO;
}
export namespace ProjectRequestDTO {
}


