/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectAllocatedResourcesDTO } from './projectAllocatedResourcesDTO';
import { ProjectStatus } from './projectStatus';
import { ObjectId } from './objectId';
import { ProjectItemDTO } from './projectItemDTO';
import { ProjectStepDTO } from './projectStepDTO';
import { RequestStatus } from './requestStatus';


export interface ProjectRequestDTO { 
    _id?: ObjectId;
    associationReqId?: string;
    associationSqlId?: number;
    projectName?: string;
    description?: string;
    budget?: number;
    requiredItemsSQLId?: Array<ProjectItemDTO>;
    projectPlan?: Array<ProjectStepDTO>;
    projectStatus?: ProjectStatus;
    status?: RequestStatus;
    approvedBy?: string;
    updatedAt?: string;
    createdAt?: string;
    allocationId?: string;
    allocatedResources?: ProjectAllocatedResourcesDTO;
}
export namespace ProjectRequestDTO {
}


