/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestStatus } from './requestStatus';
import { RequestType } from './requestType';


export interface RequestFilter { 
    requestType?: RequestType;
    associationName?: string;
    associationId?: string;
    associationConfirmed?: string;
    status?: RequestStatus;
    location?: string;
    dateFrom?: string;
    dateTo?: string;
    empty?: boolean;
}
export namespace RequestFilter {
}


