/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssociationDTO } from './associationDTO';
import { InventoryItemDTO } from './inventoryItemDTO';


export interface RequestCommonData { 
    associationsList?: Array<AssociationDTO>;
    itemsList?: Array<InventoryItemDTO>;
}

