/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestCommandType } from './requestCommandType';
import { RequestType } from './requestType';


export interface RequestCommand { 
    requestMongoId?: string;
    commandType?: RequestCommandType;
    requestType?: RequestType;
}
export namespace RequestCommand {
}


