/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RequestType = 'ASSOCIATION_REQUEST' | 'INVENTORY_REQUEST' | 'PROJECT_REQUEST' | 'VIEW_ALL_LIST';

export const RequestType = {
    AssociationRequest: 'ASSOCIATION_REQUEST' as RequestType,
    InventoryRequest: 'INVENTORY_REQUEST' as RequestType,
    ProjectRequest: 'PROJECT_REQUEST' as RequestType,
    ViewAllList: 'VIEW_ALL_LIST' as RequestType
};

