/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssociationDTO } from './associationDTO';
import { ProjectRequestDTO } from './projectRequestDTO';
import { InventoryRequestDTO } from './inventoryRequestDTO';
import { InventoryItemDTO } from './inventoryItemDTO';


export interface RequestCommonData { 
    associationsList?: Array<AssociationDTO>;
    itemMetadataMap?: { [key: string]: InventoryItemDTO; };
    itemsList?: Array<InventoryItemDTO>;
    inventoryRequestList?: Array<InventoryRequestDTO>;
    projectRequestList?: Array<ProjectRequestDTO>;
}

