/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BaseRequest } from './baseRequest';
import { InventoryRequest } from './inventoryRequest';
import { JoinRequest } from './joinRequest';
import { RequestFilter } from './requestFilter';
import { RequestType } from './requestType';


export interface RequestListResponse { 
    joinRequests?: Array<JoinRequest>;
    inventoryRequests?: Array<InventoryRequest>;
    allRequests?: Array<BaseRequest>;
    filters?: RequestFilter;
    requestTypeEnum?: RequestType;
}
export namespace RequestListResponse {
}


