/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectRequestDTO } from './projectRequestDTO';
import { InventoryRequestDTO } from './inventoryRequestDTO';
import { AssociationRequestDTO } from './associationRequestDTO';
import { RequestFilter } from './requestFilter';
import { RequestType } from './requestType';


export interface RequestListResponse { 
    associationRequests?: Array<AssociationRequestDTO>;
    /**
     * Map of string to array of inventory requests
     */
    inventoryRequests?: { [key: string]: Array<InventoryRequestDTO>; };
    /**
     * Map of string to array of project requests
     */
    projectRequests?: { [key: string]: Array<ProjectRequestDTO>; };
    filters?: RequestFilter;
    requestTypeEnum?: RequestType;
}
export namespace RequestListResponse {
}


