/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestCommandType } from './requestCommandType';
import { ProjectRequestDTO } from './projectRequestDTO';
import { InventoryRequestDTO } from './inventoryRequestDTO';
import { AssociationRequestDTO } from './associationRequestDTO';
import { RequestType } from './requestType';


export interface RequestCommand { 
    requestMongoId?: string;
    commandType?: RequestCommandType;
    requestType?: RequestType;
    projectRequestDTO?: ProjectRequestDTO;
    inventoryRequestDTO?: InventoryRequestDTO;
    associationRequestDTO?: AssociationRequestDTO;
    request?: object;
}
export namespace RequestCommand {
}


