/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RequestFilter { 
    associationName?: string;
    category?: string;
    urgency?: string;
    status?: string;
    assignedAdmin?: string;
    location?: string;
    tags?: Array<string>;
    dateFrom?: string;
    dateTo?: string;
    empty?: boolean;
}

