/**
 * nautilus-backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Variant } from './variant';
import { Expression } from './expression';
import { ParameterDeclaration } from './parameterDeclaration';


export interface Template { 
    expressions?: Array<Expression>;
    generatedId?: string;
    id?: string;
    variant?: Variant | null;
    parameterDeclarations?: Array<ParameterDeclaration>;
    fragmentIds?: Set<string>;
    fragment?: boolean;
}

