/**
 * nautilus-backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Locale } from './locale';
import { Charset } from './charset';


export interface Variant { 
    locale?: Locale;
    contentType?: string;
    encoding?: Charset;
    hashCode?: number;
    mediaType?: string;
    charset?: Charset;
}

