/**
 * nautilus-central-service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InventoryBoxDTO } from './inventoryBoxDTO';
import { WarehouseDTO } from './warehouseDTO';


export interface VirtualWarehouseResponse { 
    warehouseMap?: { [key: string]: Array<InventoryBoxDTO>; };
    warehouses?: Array<WarehouseDTO>;
    itemBoxes?: Array<InventoryBoxDTO>;
}

